traffic_light:
  version: "1"
  description: Masterskaya task fit rules by direction, specialization and traffic-light color.
  directions:
    - key: programming
      title: Программирование
      specializations:
        - key: python
          title: Питон/питон+
          green:
            - написание бэкенда для web-сайтой/обучающих платформ с базовой логикой (регистрация, ЛК)
            - CRM
            - написание API
            - создание телеграм-бота
            - создание парсера
            - автоматизация внутренних процессов
          yellow: []
          red:
            - разработка игр на unity
        - key: web_frontend
          title: Веб/Фронтенд-разработчик
          green:
            - многостраничные сайты, лендинги
            - добавление новых блоков на уже существующие сайты
            - переделка сайтов со старых технологий на наш актуальный стек
          yellow: []
          red:
            - большие проекты сайтов, где нужна разработка системы с полного нуля
            - разработка игр на unity/webgl
            - CSM (Битрикс)
        - key: testers
          title: Тестировщики
          green:
            - ручное тестирование CRM системы
            - ручное тестирование веб-приложения
            - ручное тестирование мобильного приложения (android/ios)
          yellow: []
          red:
            - автотесты (можем сделать только ручное тестирование)
        - key: cpp
          title: C++
          green:
            - интернет-магазины и CRM-системы (серверная часть)
            - утилиты и инструменты - калькулятор с расширенными функциями, парсер текстовых данных
            - работа с файлами - шифрование/расшифровка данных, подсчет строк и слов в текстовом файле
          yellow:
            - простая текстовая игра (например, крестики-нолики, змейка или угадай слово)
            - в таблице указаны лишь примеры проектов, на оценку можно приносить любой проект, необязательно из перечисленных примеров
          red:
            - сложные системы для бизнеса - ERP-системы с масштабируемой архитектурой, приложения с высокой производительностью
            - мобильные приложения/сложные игры
            - мессенджеры с шифрованием, кроссплатформенные видеозвонки
            - кроссплатформенные приложения с полноценным графическим интерфейсом
        - key: java
          title: Java
          green:
            - CRM-системы
            - B2B-продукты (если заказчик говорит, что продукт будет использоваться в корпоративной среде, можно предложить использовать Java)
            - E-commerce (если проект связан с Wildberries, Ozon, Lamoda и требует сложной логики, интеграции с маркетплейсами и агрегации данных)
            - Системы для продаж (например, автоматизация работы с заказами)
          yellow:
            - Сайты для компаний
          red:
            - высоконагруженные системы - системы с миллионами пользователей в реальном времени (например, онлайн-банкинг или соцсети) или распределенные системы с микросервисной архитектурой
            - проекты с высокой степенью безопасности - банковские системы, платежные платформы
            - обработка и анализ гигантских объемов данных с использованием технологий Big Data (Hadoop, Spark
            - разработка собственных поисковых систем или системы рекомендаций на основе искусственного интеллекта
        - key: ios
          title: IOS
          green:
            - приложения типа ЛК, каталог, оформление заказа, новостная лента, погода, читалка
          yellow:
            - если еще нет готового дизайна или дизайн системы, тогда разработка не может стартануть, сначала нужно будет отрисовывать макеты
            - если в блоке оформления заказа нужна будет доработка с оплатой, то такое скорее всего сделать не сможем
          red:
            - с нуля не сможет разработать приложение
            - аудио/видео логика (не проходили AVFoundation)
            - игры (нет SpriteKit-а)
            - мессенджеры/соцсети/видео-звонки
            - VPN
            - фоторедакторы
        - key: android
          title: ANDROID
          green:
            - приложения типа ЛК, католог, оформление заказа, новостная лента, погода, читалка
            - аудиоплееры
          yellow: []
          red:
            - онлайн-кинотеатры+читалки
            - с нуля не сможет разработать приложение
            - аудио/видео логика
            - игры
            - мессенджеры/соцсети/видео-звонки
            - VPN
            - фоторедакторы
        - key: go
          title: GO
          green:
            - приложение для управления задачами (ToDo List)
            - приложение для создания и редактирования заметок
            - сервис для мониторинга погоды
            - калькулятор валют
            - отслеживание расходов на облако
            - простой сервис для отзывов о фильмах
            - сайты компаний
            - трекер посещений сайта
          yellow:
            - в таблице указаны лишь примеры проектов, на оценку можно приносить любой проект, необязательно из перечисленных примеров
          red: []
        - key: one_c_developer
          title: 1С разработчик
          green:
            - создание и настройка управляемых форм
            - настройка оперативного учета
            - внедрение расчетов заработной платы
            - интеграция 1С с другими системами
            - создание мобильного приложения на базе 1С
            - бизнес-процессы 1С
            - базовое администрирование системы
          yellow:
            - в таблице указаны лишь примеры проектов, на оценку можно приносить любой проект, необязательно из перечисленных примеров
          red:
            - разработка крупной корпоративной системы с нуля
            - интеграция системы 1С с нестандартными внешними сервисами (API)
            - разработка сложных кастомных отчетов с нестандартной логикой
            - проектирование и развитие сложных бизнес-процессов в 1С на основе BPMN
            - адаптация или редизайн систем, работающих с большими объемами данных (ТБД)
            - тестирование интеграций 1С с различными платформами
        - key: fullstack
          title: Фулстек-разработчик
          green:
            - сайт заметок с авторизацией
            - список задач
            - простой интернет-магазин
            - простой блог или API для блога
            - система регистрации и авторизации
            - калькулятор валют
          yellow:
            - в таблице указаны лишь примеры проектов, на оценку можно приносить любой проект, необязательно из перечисленных примеров
          red:
            - высоконагруженные и масштабные системы
            - реализация микросервисной архитектуры с нуля
            - системы, требующие глубоких знаний в кибербезопасности
            - комплексные AI/ML интеграции
    - key: design
      title: Дизайн
      specializations:
        - key: ux_ui_designer
          title: Дизайнер интерфейсов (UX/UI)
          green:
            - Доработка интерфейса - десктоп и моб. приложения
            - Создание дизайн-макетов сайтов и приложений
            - Разработка айдентики (логотип, подбор шрифта, фирменные цвета)
            - Создание дизайн-макетов мобильного приложения
            - Создание одностраничного сайта (лендинга)
            - Создание презентаций, графиков и таблиц на основе данных
            - Кликабельные прототипы сайтов и приложений в Figma
            - Создание статичных креативов
          yellow:
            - Использование нейросетей для создания контента
          red:
            - Сборка сайта на Тильде (студенты знают только основы, с которыми будет трудно сделать верстку)
            - Использование сторонних сервисов для анимаций решений (Adobe After Effects, Principle и другие)
            - Использование 3D визуализации (Cinama 4D, Spline и др)
        - key: graphic_designer
          title: Графический дизайнер
          green:
            - Разработка логотипов
            - Разработка фирменного стиля
            - Типографика
            - Разработка концепции
            - Анимация Adobe After Effects
            - Дизайн упаковки
            - Дизайн полиграфии
            - Создание презентаций
            - Дизайн социальных сетей
            - Брендбук
          yellow: []
          red: []
        - key: web_designer
          title: Веб-дизайнер
          green:
            - Исследовать конкурентов, целевую аудиторию и её привычки
            - Лендинги и вайрфреймы
            - Работа с цветом и поиск и стилизация изображений
            - UX-копирайтинг
            - Анимации
          yellow: []
          red: []
        - key: motion_designer
          title: Моушен-дизайнер
          green:
            - простая рекламная анимация
            - интро для YouTube-канала
            - анимированный логотип
            - анимация для соцсетей
            - монтаж учебного или промо-ролика
          yellow:
            - 3D-модель с базовой анимацией
            - визуализация продукта
            - анимация персонажа (простая)
            - постеры с динамическими элементами
          red:
            - сложная 3D-анимация
            - сложный видеомонтаж с использованием эффектов VFX
            - разработка игры или игровых анимаций
            - комплексные AR/VR-проекты
    - key: analytics
      title: Аналитика
      specializations:
        - key: data_analyst
          title: Data Analyst (DA)
          green:
            - А/В-тестирование
            - Предобработка данных
            - Юнит-экономика
            - Работа с несколькими источниками данных - SciPy и Matplotlib
            - Когортный анализ
          yellow:
            - Задачи с активным использованием Excel
          red:
            - 1С
            - MS SQ
            - Power BI
        - key: data_science
          title: Data Science (DS)
          green:
            - Предобработка данных
            - Моделирование и машинное обучение
            - Градиентный бустинг и спуск
            - Паттерны решения задачи
            - Кластеризация
            - Компьютерное зрение (CV)
            - Машинное обучение для текстов
          yellow:
            - Git
            - математическая статистика и теория вероятности
            - NLP
            - обучение нейросети (плюсовые программы)
          red:
            - выстраивания автоматизированных ML-пайплайнов
        - key: system_analyst
          title: Системный аналитик (CA)
          green:
            - Моделирование процессов
            - Диаграмма бизнес-процессов в BPMN
            - Составление User / Job Story
            - Моделирование данных
            - Построение ER-диаграммы
          yellow:
            - Технологии разработки пользовательских интерфейсов (HTML, CSS, JS), проектирование UX - разработка UJM, Языки программирования, Модель C4 (только расширенный), Микросервисная архитектура (только расширенный), Событийная архитектура (только расширенный), Query-based API (только расширенный), ASYNC API (только расширенный)
          red:
            - CustDev
        - key: business_analyst
          title: Бизнес-аналитик (BA)
          green:
            - Расчет экономического эффекта
            - Прогнозирование результатов
            - Моделирование бизнес-процессов
            - Анализ и описание бизнес-процессов
            - Постановка задач разработке
            - Проработка пользовательских сценариев
          yellow: []
          red:
            - Системный анализ
            - Статистический и матанализ
            - Анализ рынка и конкурентов
        - key: data_engineer
          title: Инженер данных (DE)
          green:
            - построение DWH с нуля на реляционной СУБД
            - построение простого хранилища данных в Vertica
            - Потоковая обработка данных
            - автоматизировать масштабирование систем с помощью облачных сервисов
            - Формирование витрин БД
          yellow:
            - выстраивания автоматизированных ML-пайплайнов
            - Работа с матрицами
          red:
            - Сбор данных
            - Веб-скрапинг
        - key: one_c_analyst
          title: 1С аналитик
          green:
            - моделирование бизнес-процессов
            - составление ТЗ на доработку 1С:ERP
            - настройка отчетов в СКД
            - мэппинг данных для интеграции
            - разработка инструкций для пользователей
            - контроль SLA
          yellow: []
          red:
            - сложная интеграция 1С с другими системами
            - оптимизация высоконагруженных систем
            - проектирование архитектуры системы
            - анализ и решение сложных бухгалтерских или налоговых задач
    - key: marketing
      title: Маркетинг
      specializations:
        - key: internet_marketer
          title: Интернет-маркетолог
          green:
            - Расчёт метрик, когортный анализ, составление маркетинговой воронки
            - Анализ конкурентов
            - Составление медиапланов
            - Понимание всех digital каналов продвижения, а также ATL/BTL рекламы
            - Настройка рекламных кабинетов в Яндекс Директ, VK, MyTarget
            - Создание креативов для рекламы и постановка ТЗ на креативы
            - Понимание веб-аналитики, анализ Яндекс Метрики, Google Analytics
            - Понимание ключевых процессов SEO оптимизации
            - Понимание Email маркетинга, создания рассылок, Понимание CRM маркетинга
          yellow: []
          red:
            - Составление маркетинговой стратегии всей компании , составление стратегии бренда
            - Анализ бренда (POP / POD) и бренд стратегия
            - Работа с бюджетами (есть только понимание)
            - Полноценная оптимизация рекламных кампаний, ABC анализ и A/B тестирование
            - Полноценная настройка SEO, работа с серыми программа SEO
            - Выбор и расчет эффективности в разных каналах коммуникации
            - Брифование клиента и работа с ключевыми клиентами в маркетинговом агенствае
        - key: marketing_workshop_limits
          title: Мастерская пока не может взять задачи, связанные с анализом рынка и исследованием конкурентов. В данный момент мы можем сосредоточиться на задачах, касающихся привлечения аудитории, работы с рекламными системами, веб-аналитики и взаимодействия с маркетплейсами.
          green: []
          yellow: []
          red: []
        - key: traffic_manager
          title: Трафик-менеджер
          green:
            - Настройка рекламных кабинетов в Яндекс Директ, Google Ads, ВКонтакте, MyTarget
            - Аналитика рекламных кампаний в Яндекс Метрике, Google Analytics
          yellow: []
          red:
            - Работа с Telegram (в тч посевы)
            - Мобильный трафик и аналитика, mobile, in-app трафик
            - Закупка трафика в CPA сетях
            - Арбитражный трафик
        - key: brand_manager
          title: Бренд-менеджер
          green:
            - Целеполагание и анализ рынка
            - Анализ конкурентов и потребителей
            - Стратегии развития бренда, создание платформы, айдентика, проектирование ассортимента
            - Коммуникация бренда (точки контакта бренда с потребителем, каналы коммуникации, коммуникационная стратегия)
            - Диджитал-каналы развития и продвижения бренда, основы медиапланирования бренда, основы электронной коммерции
            - Оценка эффективности бренда
            - Работа с финансами
          yellow: []
          red: []
        - key: content_marketer
          title: Контент-маркетолог
          green:
            - Создание контент-стратегии
            - Проведение маркетинговых исследований (рынок, конкуренты, аудитория, продукт)
            - Анализ маркетинговой воронки
            - Производство контента
            - Медиапланирование
            - Управление контент-проектом
            - Управление командами
            - Дистрибуция контента по каналам и площадкам
            - Анализ работы контента и его оптимизация
          yellow: []
          red: []
        - key: smm_specialist
          title: SMM-специалист
          green:
            - Маркетинговый анализ (рынок, тренды, аудитория, конкуренты, продукт)
            - Анализ аудтории и сегментов в социальных сетях
            - Работа с аудиторией, удержание
            - Продвижение бренда в социальных сетях, послание бренда, ToV
            - Бесплатное продвижение в социальных сетях
            - Платное продвижение ВКонтакте, Telegram, Дзен, Одноклассники
            - Общение с блогерами и инфлюенсерами
            - Создание текстового и визуального контента
            - Копирайтинг
            - Ведение социальных сетей
            - Анализ эффективности SMM
          yellow: []
          red: []
        - key: marketplace_manager
          title: Менеджер маркетплейсов
          green:
            - Разбираются в основных маркетплейсах - WB, Ozon, Яндекс Маркет, СберМегамаркет, Lamoda
            - Создание карточек товаров
            - Оптимизация карточек товаров (SEO)
            - Продвижение и реклама на маркетплейсах
            - Понимают виды логистики, налогообложения
            - Могут оценивать маржинальность
          yellow: []
          red:
            - Закупка товаров и выбор поставщиков
            - Логистика и транспорт товаров, упаковка
            - Работа со складами и запасами, ТМЗ
            - Работа с локальными маркетплейсами
    - key: management
      title: Менеджмент
      specializations:
        - key: product_manager
          title: Product-менеджер
          green:
            - Проведение исследования рынка - конкурентов, аудитории, трендов, размера.
            - Проводит продуктовые исследования - глубинные интервью, опросы, юзабилити-тестирования.
            - Работает с продуктовой аналитикой - умеет настраивать инструменты для сбора данных, получать нужные данные, рассчитывать значения метрик.
            - Умеет считать MAU, DAU, LTV, retention, CAC, ROI.
            - Создает базовый дизайн цифровых продуктов - знает принципы, создает user flow, mid-fi прототипы.
            - Определяет MVP, MLP и целевую версию продукта - создает Roadmap (MVP, MLP, целевой продукт), может проанализировать риски, способ их минимизации, может интегрировать риски в Roadmap.
          yellow: []
          red: []
        - key: management_note
          title: "Примечание: проджекта здесь прикладывать, кажется, бесполезно. Но оставлю ссылку на его скиллсет. Также мы не работаем с IT-рекрутерами и HR-менеджерами. Но прикладываю здесь их скиллсеты, которые тоже получил у коллег"
          green:
            - https://wiki.yandex-team.ru/practicum/management/karernyjjc-dc1e/rabocheepr-45f9/skillsetme-1cd8/
            - https://wiki.yandex-team.ru/practicum/management/karernyjjc-dc1e/rabocheepr-45f9/skillsetit-1c93/
            - https://wiki.yandex-team.ru/practicum/management/karernyjjc-dc1e/rabocheepr-45f9/skillsethr-d71a/
          yellow: []
          red: []
